// Generated by tools/make_fonts.py - Latin + Cyrillic fonts
#pragma once
#include "../lgfx_config.h"
#include "LibSans13.h"
#include "LibSans17.h"
#include "LibSans25.h"
#include "LibSans34.h"
#include "LibSans50.h"
#include "LibSans68.h"
#include "LibSerif13.h"
#include "LibSerif17.h"
#include "LibSerif25.h"
#include "LibSerif34.h"
#include "LibSerif50.h"
#include "LibSerif68.h"
#include "LibMono13.h"
#include "LibMono17.h"
#include "LibMono25.h"
#include "LibMono34.h"
#include "LibMono50.h"
#include "LibMono68.h"
static const lgfx::IFont *FONTS_SANS[6] = {&LibSans13, &LibSans17, &LibSans25, &LibSans34, &LibSans50, &LibSans68};
static const lgfx::IFont *FONTS_SERIF[6] = {&LibSerif13, &LibSerif17, &LibSerif25, &LibSerif34, &LibSerif50, &LibSerif68};
static const lgfx::IFont *FONTS_MONO[6] = {&LibMono13, &LibMono17, &LibMono25, &LibMono34, &LibMono50, &LibMono68};
