#!/usr/bin/env python3
"""
Generates Adafruit-GFX style fonts (used by LovyanGFX) with Latin + Cyrillic.
Output: src/fonts/*.h  and  src/fonts/fonts.h

Glyph range is contiguous U+0020..U+045F; only ASCII, the degree sign and
Cyrillic (U+0400..U+045F) get real bitmaps, everything else is empty.

usage: python3 tools/make_fonts.py   (needs Pillow and the Liberation fonts)
"""
import os
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x45F
FAMILIES = {
    "Sans": "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "Serif": "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf",
    "Mono": "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
}
CAP_HEIGHTS = [13, 17, 25, 34, 50, 68]  # size levels 1..6 (7 and 8 are 5 and 6 drawn at 2x)
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "fonts")


def wanted(cp):
    return 0x20 <= cp <= 0x7E or cp == 0xB0 or 0x400 <= cp <= 0x45F


def font_for_cap(path, cap):
    size = cap
    while True:
        f = ImageFont.truetype(path, size)
        x0, y0, x1, y1 = f.getbbox("H", anchor="ls")
        if -y0 >= cap:
            return f
        size += 1


def glyph(f, ch):
    adv = round(f.getlength(ch))
    x0, y0, x1, y1 = f.getbbox(ch, anchor="ls")
    w, h = x1 - x0, y1 - y0
    if w <= 0 or h <= 0:
        return adv, 0, 0, 0, 0, b""
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=f, fill=255, anchor="ls")
    px = img.load()
    # trim empty borders
    rows = [y for y in range(h) if any(px[x, y] >= 110 for x in range(w))]
    cols = [x for x in range(w) if any(px[x, y] >= 110 for y in range(h))]
    if not rows:
        return adv, 0, 0, 0, 0, b""
    top, bot, left, right = rows[0], rows[-1], cols[0], cols[-1]
    bits = []
    for y in range(top, bot + 1):
        for x in range(left, right + 1):
            bits.append(1 if px[x, y] >= 110 else 0)
    data = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j, b in enumerate(bits[i:i + 8]):
            byte |= b << (7 - j)
        data.append(byte)
    gw, gh = right - left + 1, bot - top + 1
    xo, yo = x0 + left, y0 + top
    assert gw < 256 and gh < 256 and -128 <= xo < 128 and -128 <= yo < 128 and adv < 256, (ch, gw, gh, xo, yo)
    return adv, gw, gh, xo, yo, bytes(data)


def build(name, path, cap):
    f = font_for_cap(path, cap)
    asc, desc = f.getmetrics()
    bitmap = bytearray()
    glyphs = []
    for cp in range(FIRST, LAST + 1):
        if not wanted(cp):
            glyphs.append((0, 0, 0, 0, 0, 0))
            continue
        adv, w, h, xo, yo, data = glyph(f, chr(cp))
        glyphs.append((len(bitmap), w, h, adv, xo, yo))
        bitmap += data
    ident = f"Lib{name}{cap}"
    lines = [f"// Liberation {name} Bold, cap height {cap}px, U+0020..U+045F (ASCII + Cyrillic)",
             "#pragma once", ""]
    lines.append(f"static const uint8_t {ident}_bitmap[] PROGMEM = {{")
    for i in range(0, len(bitmap), 24):
        lines.append("  " + ",".join(f"0x{b:02X}" for b in bitmap[i:i + 24]) + ",")
    lines.append("  0x00};")
    lines.append(f"static const lgfx::GFXglyph {ident}_glyphs[] PROGMEM = {{")
    for g in glyphs:
        lines.append("  {%d,%d,%d,%d,%d,%d}," % g)
    lines.append("};")
    lines.append(f"static const lgfx::GFXfont {ident}((uint8_t *){ident}_bitmap, (lgfx::GFXglyph *){ident}_glyphs, "
                 f"0x{FIRST:X}, 0x{LAST:X}, {min(255, asc + desc)});")
    with open(os.path.join(OUT, ident + ".h"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return ident, len(bitmap)


def main():
    os.makedirs(OUT, exist_ok=True)
    idents, total = {}, 0
    for fam, path in FAMILIES.items():
        idents[fam] = []
        for cap in CAP_HEIGHTS:
            ident, size = build(fam, path, cap)
            idents[fam].append(ident)
            total += size + (LAST - FIRST + 1) * 12
    with open(os.path.join(OUT, "fonts.h"), "w") as fh:
        fh.write("// Generated by tools/make_fonts.py - Latin + Cyrillic fonts\n#pragma once\n#include \"../lgfx_config.h\"\n")
        for fam in idents:
            for i in idents[fam]:
                fh.write(f'#include "{i}.h"\n')
        for fam in idents:
            fh.write(f"static const lgfx::IFont *FONTS_{fam.upper()}[{len(CAP_HEIGHTS)}] = {{"
                     + ", ".join("&" + i for i in idents[fam]) + "};\n")
    print(f"approx flash use: {total / 1024:.0f} KB")


if __name__ == "__main__":
    main()
